package com.thinkmobiles.bodega.db.daogen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.thinkmobiles.bodega.db.daogen.OrderItem;
import com.thinkmobiles.bodega.db.daogen.Customer;

import com.thinkmobiles.bodega.db.daogen.OrderItemDao;
import com.thinkmobiles.bodega.db.daogen.CustomerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderItemDaoConfig;
    private final DaoConfig customerDaoConfig;

    private final OrderItemDao orderItemDao;
    private final CustomerDao customerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderItemDaoConfig = daoConfigMap.get(OrderItemDao.class).clone();
        orderItemDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        orderItemDao = new OrderItemDao(orderItemDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);

        registerDao(OrderItem.class, orderItemDao);
        registerDao(Customer.class, customerDao);
    }
    
    public void clear() {
        orderItemDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
    }

    public OrderItemDao getOrderItemDao() {
        return orderItemDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

}
